name: "Build"

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - certs.sh
      - .github/workflows/build.yaml

permissions:
  contents: 'read'
  id-token: 'write'
  packages: write

jobs:
  packaging:
    strategy:
      fail-fast: false
      matrix:
        version: [ '1.0.0' ]
        latest: [ true ]
    runs-on: ubuntu-latest
    name: "[Build] Self-signed certificate"
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"

      - name: Login to GitHub Container Registry
        uses: 'docker/login-action@v1'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_REPOSITORY_TOKEN }}

      - name: Process builder
        shell: bash
        run: |
          echo "build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Set up Depot CLI
        uses: 'depot/setup-action@v1'

      - name: Build and Push Package
        uses: 'depot/build-push-action@v1'
        with:
          project: ${{ secrets.DEPOT_PROJECT_ID }}
          token: ${{ secrets.DEPOT_PROJECT_TOKEN }}
          push: true
          provenance: false
          sbom: false
          tags: |
            ghcr.io/devgine/selfsigned-certificate:${{ matrix.version }}
            ${{ matrix.latest && 'ghcr.io/devgine/selfsigned-certificate:latest' || ''}}
          context: .
          file: ./Dockerfile
          build-args: |
            VCS_REF=${{ github.sha }}
            BUILD_DATE=${{ env.build_date }}
            BUILD_VERSION=v${{ matrix.version }}
            IMAGE_TAG=ghcr.io/devgine/selfsigned-certificate:${{ matrix.version }}

  generation:
    strategy:
      fail-fast: false
      matrix:
        version: ['1.0.0', 'latest']
    needs: packaging
    runs-on: ubuntu-latest
    name: "[Generate] Self-signed certificate (${{ matrix.version }})"
    container:
      image: ghcr.io/devgine/selfsigned-certificate:${{ matrix.version }}
    steps:
      - name: Print software version
        run: docker-certs -V

      - name: Print the script help
        run: docker-certs -h

      - name: Generate self-signed certificate
        run: docker-certs -d www.prod.com -d "*.dev.web"

# todo: check certificates exists